# Generated by Django 4.1.5 on 2023-01-26 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, upload_to='user_icons/'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 1, 56, 59, 898015)),
        ),
    ]
