# Generated by Django 4.1.5 on 2023-01-27 00:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_customuser_icon_alter_userpost_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpost',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 2, 2, 35, 122580)),
        ),
    ]
